title: Goodness To Go
baseURL: /
params:
  description: Goodness to Go Sample Site
  layout_type: full-width
  style: classic
  palette: blue
  mode: light
  base_font: sans-serif
  header:
    type: header
    template: header
    title: Goodness To Go
    logo: /images/baking-icon.jpg
    logo_alt: Goodness To Go logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        template: action
        label: Menus
        url: /menu
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: About
        url: /about
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Blog
        url: /blog
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        template: action
        label: Contact
        url: /contact
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Order Now
        url: /menu
        style: primary
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_anncmnt: true
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
      More](/pricing/)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    type: footer
    template: footer
    logo: /images/baking-icon.jpg
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_title: Company
    primary_nav_links:
      - type: action
        template: action
        label: About
        url: /about
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Style Guide
        url: /style-guide
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - type: action
        template: action
        label: News
        url: /blog/category/news
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: General
        url: /blog/category/general
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Tutorials
        url: /blog/category/tutorials
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_tertiary_nav: true
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - type: action
        template: action
        label: Terms & Conditions
        url: /terms-conditions
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
      - type: action
        template: action
        label: Privacy Policy
        url: /privacy-policy
        style: link
        has_icon: false
        icon: ''
        icon_position: ''
        new_window: false
        no_follow: false
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/EamonnCottrell'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
        no_follow: false
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/in/EamonnCottrell'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
        no_follow: false
      - type: action
        template: action
        label: YouTube
        url: 'https://www.youtube.com/'
        style: link
        has_icon: true
        icon: youtube
        icon_position: center
        new_window: true
        no_follow: false
      - label: Facebook
        url: 'https://www.facebook.com/lunchladiesgoodnesstogo/'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
        no_follow: false
        type: action
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=diy&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
    links: []
  favicon: /images/energetic-saturn.jpg
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
